hiero.accountId=${HIERO_OPERATOR_ACCOUNT}
hiero.privateKey=${HIERO_OPERATOR_PRIVATE_KEY}
hiero.network.name=${HIERO_NETWORK:localhost}
hiero.network.nodes=127.0.0.1:50211:0.0.3
hiero.network.mirrornode=http://localhost:5551
